/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    update
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_update
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HelloJNI
 * Method:    add
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_add
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     HelloJNI
 * Method:    delete
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJNI
 * Method:    user_list
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_user_1list
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    borrow
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_borrow
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     HelloJNI
 * Method:    Return
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_Return
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     HelloJNI
 * Method:    myBooks
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_myBooks
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    checkuser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_HelloJNI_checkuser
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     HelloJNI
 * Method:    checkadmin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_HelloJNI_checkadmin
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
